
name: first workflow
on:
  push
   
jobs:
  echo-statement:
    runs-on: ubuntu-latest
    steps:
     - name: Echo
       run: echo "hello,githubactins"
  diplay-info:
    runs-on: windows-latest
    steps:
     - name: Echo
       run: echo "windows"
     
    

    
